trigger:
  branches:
    include:
    - main
    - feature/*
  paths:
    include:
    - terraform/**
    - terragrunt/**

parameters:
  - name: action
    displayName: |
      🔧 Ação a executar:
      - init: Inicializa o Terragrunt
      - validate: Valida a configuração
      - plan: Gera plano de execução
      - apply: Aplica mudanças
      - destroy: Remove infraestrutura
      - output: Mostra outputs
    default: plan
    type: string
    values:
      - init
      - validate
      - plan
      - apply
      - destroy
      - output
  - name: environment
    displayName: '🌐 Ambiente'
    default: 'dev'
    type: string
    values:
      - dev
      - hml
      - prod

  - name: region
    displayName: '🌍 Região'
    default: 'eastus2'
    type: string
    values:
      - eastus2
      - brazilsouth

variables:
  # Variáveis do ambiente
  TERRAFORM_VERSION: '1.10.5'
  TERRAGRUNT_VERSION: '0.73.14'
  
  # Definir ambiente default (será substituído pelos parâmetros do pipeline)
  ENV_NAME: ${{ parameters.environment }}
  REGION: ${{ parameters.region }}
  
  # Configurações do backend (opcional, pode ser substituído pelas variáveis de ambiente ARM_*)
  TF_STATE_RG: 'rg-terragrunt-state'
  TF_STATE_SA: 'stterragruntstate'
  TF_STATE_CONTAINER: 'tg-tfstate'

stages:
- stage: Infrastructure
  displayName: '🏗️ Infraestrutura como Código'
  jobs:
  - job: TerragruntJob
    displayName: '🚀 Terragrunt ${{ parameters.action }}'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    # Instalar Terraform e Terragrunt apenas uma vez por job
    - bash: |
        echo "Instalando Terraform v$(TERRAFORM_VERSION)..."
        curl -LO "https://releases.hashicorp.com/terraform/$(TERRAFORM_VERSION)/terraform_$(TERRAFORM_VERSION)_linux_amd64.zip"
        sudo apt-get update && sudo apt-get install -y unzip
        unzip terraform_$(TERRAFORM_VERSION)_linux_amd64.zip
        sudo mv terraform /usr/local/bin/
        terraform --version

        echo "Instalando Terragrunt v$(TERRAGRUNT_VERSION)..."
        curl -LO "https://github.com/gruntwork-io/terragrunt/releases/download/v$(TERRAGRUNT_VERSION)/terragrunt_linux_amd64"
        chmod +x terragrunt_linux_amd64
        sudo mv terragrunt_linux_amd64 /usr/local/bin/terragrunt
        terragrunt --version
      displayName: '⚙️ Instalar Terraform e Terragrunt'

    # Validação de código (somente quando a ação não é destroy)
    - bash: |
        echo "Formatando e validando arquivos Terraform..."
        terraform fmt --check --recursive ./terraform || true
        
        echo "Formatando e validando arquivos Terragrunt..."
        terragrunt hclfmt --check --working-dir ./terragrunt || true
      # terragrunt hclvalidate --working-dir ./terragrunt || true
      displayName: '✅ Validar formatação e sintaxe'
      condition: and(succeeded(), ne('${{ parameters.action }}', 'destroy'))

    # Executar ação do Terragrunt baseada no parâmetro
    - task: AzureCLI@2
      displayName: '🔄 Terragrunt ${{ parameters.action }}'
      inputs:
        azureSubscription: 'SP-MPN'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          set -e
          echo "Executando Terragrunt ${{ parameters.action }} para $(ENV_NAME) em $(REGION)"
          
          # Navegando para o diretório do ambiente
          cd terragrunt/environments/$(ENV_NAME)/$(REGION)
          
          # Executando a ação solicitada
          case "${{ parameters.action }}" in
            init)
              terragrunt run-all init --non-interactive
              ;;
            validate)
              terragrunt run-all validate --non-interactive
              ;;
            plan)
              # Criar diretório para planos
              mkdir -p $(Build.ArtifactStagingDirectory)/plans
              
              # Gerar plano detalhado
              terragrunt run-all plan --non-interactive --out=$(Build.ArtifactStagingDirectory)/plans/tfplan.binary
              
              # Criar resumo legível do plano
              cd $(Build.ArtifactStagingDirectory)/plans
              if [ -f "tfplan.binary" ]; then
                terraform show -no-color tfplan.binary > plan.txt
                echo "Resumo do plano:" > plan_summary.txt
                cat plan.txt | grep -E 'Plan:|will be created|will be destroyed|will be updated' >> plan_summary.txt
                echo "---"
                cat plan_summary.txt
              fi
              ;;
            apply)
              terragrunt run-all apply --non-interactive --auto-approve
              ;;
            destroy)
              terragrunt run-all destroy --non-interactive --auto-approve
              ;;
          esac

    # Publicar artefatos se estiver em modo de plano
    - task: PublishPipelineArtifact@1
      displayName: '📦 Publicar artefatos do plano'
      inputs:
        targetPath: '$(Build.ArtifactStagingDirectory)/plans'
        artifact: 'TerraformPlan'
        publishLocation: 'pipeline'
      condition: and(succeeded(), eq('${{ parameters.action }}', 'plan'))

    # Outputs em caso de apply
    - bash: |
        if [ "${{ parameters.action }}" == "apply" ]; then
          echo "Coletando outputs..."
          cd terragrunt/environments/$(ENV_NAME)/$(REGION)
          terragrunt run-all output --non-interactive || true
        fi
      displayName: '📋 Mostrar outputs (somente apply)'
      condition: and(succeeded(), eq('${{ parameters.action }}', 'apply'))

- stage: Validation
  displayName: '🔍 Validação'
  dependsOn: Infrastructure
  # Somente executar estágio de validação após aplicar mudanças em produção
  condition: and(succeeded(), eq('${{ parameters.action }}', 'apply'), eq('${{ parameters.environment }}', 'prod'))
  jobs:
  - job: ValidationJob
    displayName: '✓ Validar Implantação'
    pool: server
    steps:
    - task: ManualValidation@1
      timeoutInMinutes: 1440 # 24 horas
      inputs:
        notifyUsers: '$(BUILD_REQUESTEDFOR)'
        instructions: 'Por favor, valide a implantação em produção e confirme se está tudo correto.'
        onTimeout: 'resume'